version: '3.8'

services:
  postgres:
    image: postgres:13
    container_name: postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    expose:
      - "5432"  # 👈 only expose inside the docker network
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app_net

  superset:
    image: apache/superset:latest
    container_name: superset
    environment:
      - SUPERSET_SECRET_KEY=supersecret
    ports:
      - "8088:8088"
    depends_on:
      - postgres
    command: >
      /bin/sh -c "
        superset db upgrade &&
        superset fab create-admin --username admin --firstname Superset --lastname Admin --email admin@superset.com --password admin &&
        superset init &&
        superset run -h 0.0.0.0 -p 8088
      "
    volumes:
      - superset_home:/app/superset_home
    networks:
      - app_net

volumes:
  postgres_data:
  superset_home:

networks:
  app_net:
